### ISSUE TITLE
Ollama support?

### ISSUE THREAD

**Issue by jguhlin** [jeremychone/rust-devai#1]
How do you set it to use a local Ollama model? Cheers

**Comment by jeremychone** [comment]
Install the latest, `0.0.10`, where I fixed some bugs.  
Remove your `.devai/config.toml`  
Run `devai init` to recreate `.devai/config.toml`

You can see an Ollama example in the comment.

In short, it's using the [genai crate](https://crates.io/crates/genai) and the fallback will be Ollama.

**Comment by jeremychone** [comment]
@jguhlin I tested it and it work nicely. I am going to close this ticket, but feel free to create a new issue if you have any issues with it.
